name: macOS CI

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: |
          sudo xcode-select -s "/Applications/Xcode.app/Contents/Developer" || true
          xcodebuild -version

      - name: Build (debug)
        run: swift build -v

      - name: Test (debug)
        run: swift test -v

      - name: Build (release)
        run: swift build -c release

      - name: Run CLI (redacted)
        shell: bash
        run: |
          BIN=".build/release/serial-number"
          if [[ ! -x "$BIN" ]]; then BIN=".build/debug/serial-number"; fi
          if [[ ! -x "$BIN" ]]; then echo "Binary not found"; exit 1; fi
          OUT=$($BIN || true)
          if [[ -z "$OUT" ]]; then echo "No output from CLI"; exit 1; fi
          echo "CLI produced non-empty output (length=${#OUT})"

